# Form implementation generated from reading ui file 'interface_v2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.resize(521, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(521, 550))
        Form.setMaximumSize(QtCore.QSize(521, 550))
        Form.setMouseTracking(False)
        Form.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("#Form{\n"
"background-color:rgb(239, 239, 239);\n"
"}\n"
"QFrame{\n"
"padding: 0px 0px 0px 0px;\n"
"}\n"
"QTableWidget{\n"
" color: rgb(0,0,0);\n"
"    background: rgba(255, 255, 255,1);\n"
"    border: 1px solid rgba(255, 255, 255,1);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"     /*border-radius: 5px;*/\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    /*padding: 5px 12px 6px 12px;*/\n"
"    outline: none;\n"
"}\n"
"QGroupBox{\n"
" color: rgb(0,0,0);\n"
"    background: rgba(250, 250, 250, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    /*padding: 5px 12px 6px 12px;*/\n"
"   outline: none;\n"
"}\n"
"QPushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
"    color: rgb(0,0,0);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"/*    border-bottom: 1px solid rgba(0, 0, 0, 0.183);*/\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"QPushButton:checked {\n"
"    color: white;\n"
"    background-color: #00aa5e;\n"
"    border: 1px solid #00b348;\n"
"    border-bottom: 1px solid #00803c;\n"
"}\n"
"QSpinBox, QDoubleSpinBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 0px 0 0px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover,\n"
"QDoubleSpinBox:hover{\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus{\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled{\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 0px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"QTextEdit,\n"
"QPlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"QLineEdit:hover, QTextEdit:hover, QPlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"QTextEdit:focus,\n"
"QPlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:disabled, QTextEdit:disabled,\n"
"QPlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"QCheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QCheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked:hover,\n"
"QCheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed,\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QCheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}\n"
"\n"
"#lasterror_l{\n"
"border : 1px solid rgba(255,255,255,1);\n"
"}\n"
"\n"
"#buy {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 137, 239);\n"
"border-bottom-right-radius:0 ;\n"
"border-top-right-radius:0 ;\n"
"\n"
"    font-weight: bold;\n"
"}\n"
"#buy:hover{\n"
"background-color: rgba(45, 137, 239, 0.8);\n"
"}\n"
"#buy:pressed{\n"
"background-color:  rgba(45, 137, 239, 0.7);\n"
"}\n"
"\n"
"#halfbuy {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 129, 222);\n"
"border-bottom-left-radius:0 ;\n"
"\n"
"    font-weight: bold;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#halfbuy:hover{\n"
"background-color: rgba(41, 129, 222, 0.8);\n"
"}\n"
"#halfbuy:pressed{\n"
"background-color:  rgba(41, 129, 222, 0.7);\n"
"}\n"
"#sell {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(238, 17, 17);\n"
"\n"
"    font-weight: bold;\n"
"border-bottom-left-radius:0 ;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#sell:hover{\n"
"background-color: rgba(238, 17, 17, 0.8);\n"
"}\n"
"#sell:pressed{\n"
"background-color:  rgba(238, 17, 17, 0.7);\n"
"}\n"
"#halfsell {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(216, 15, 15);\n"
"\n"
"    font-weight: bold;\n"
"border-bottom-right-radius:0 ;\n"
"border-top-right-radius:0 ;\n"
"}\n"
"#halfsell:hover{\n"
"background-color: rgba(216, 15, 15, 0.8);\n"
"}\n"
"#halfsell:pressed{\n"
"background-color:  rgba(216, 15, 15, 0.7);\n"
"}\n"
"#avatar_image{\n"
"border: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"#nownews_l{\n"
"color:green;\n"
"font-weight:bold;\n"
"border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-radius: 10px;\n"
"background-color:  rgba(75, 245, 66, 0.2);\n"
"}\n"
"#chart_frame{\n"
"font-weight:bold;\n"
"border: 1px solid rgba(0, 0, 0, 0.5);\n"
"    border-radius: 10px;\n"
"border-bottom-left-radius:0 ;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#frame_8{\n"
"font-weight:bold;\n"
"border: 1px solid rgba(0, 0, 0, 0.5);\n"
"    border-radius: 10px;\n"
"border-bottom-left-radius:0 ;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#show_chart_f{\n"
"font-weight:bold;\n"
"border: 1px solid rgba(0, 0, 0, 0.5);\n"
"    border-radius: 10px;\n"
"border-bottom-right-radius:0 ;\n"
"border-top-right-radius:0 ;\n"
"border-bottom-left-radius:0 ;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#show_chart_b{\n"
"border-bottom-left-radius:0 ;\n"
"border-top-left-radius:0 ;\n"
"}\n"
"#show_calendar_b{\n"
"border-bottom-right-radius:10px ;\n"
"border-top-right-radius:0 ;\n"
"}\n"
"#pos_tree{\n"
" border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    /*border-radius: 10px;*/\n"
"}\n"
"#show_statement_b{\n"
"padding: 0px 0px 0px 0px;\n"
"}")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 263, 231, 130))
        self.groupBox_3.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.currentprofit_l = QtWidgets.QLabel(parent=self.groupBox_3)
        self.currentprofit_l.setGeometry(QtCore.QRect(100, 10, 41, 16))
        self.currentprofit_l.setStyleSheet("color: rgb(0, 163, 0);")
        self.currentprofit_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.currentprofit_l.setObjectName("currentprofit_l")
        self.drawdown_l = QtWidgets.QLabel(parent=self.groupBox_3)
        self.drawdown_l.setGeometry(QtCore.QRect(80, 30, 41, 16))
        self.drawdown_l.setStyleSheet("color: rgb(0, 163, 0);")
        self.drawdown_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drawdown_l.setObjectName("drawdown_l")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.connection_l = QtWidgets.QLabel(parent=self.groupBox_3)
        self.connection_l.setGeometry(QtCore.QRect(80, 50, 91, 16))
        self.connection_l.setStyleSheet("color: rgb(238, 17, 17);")
        self.connection_l.setObjectName("connection_l")
        self.lasterror_l = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.lasterror_l.setGeometry(QtCore.QRect(70, 70, 151, 46))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lasterror_l.setFont(font)
        self.lasterror_l.setStyleSheet("color:rgb(255, 255, 255);")
        self.lasterror_l.setReadOnly(True)
        self.lasterror_l.setObjectName("lasterror_l")
        self.trade_g = QtWidgets.QGroupBox(parent=Form)
        self.trade_g.setGeometry(QtCore.QRect(10, 10, 231, 141))
        self.trade_g.setObjectName("trade_g")
        self.halfbuy = QtWidgets.QPushButton(parent=self.trade_g)
        self.halfbuy.setGeometry(QtCore.QRect(187, 20, 41, 41))
        self.halfbuy.setAutoFillBackground(False)
        self.halfbuy.setStyleSheet("")
        self.halfbuy.setObjectName("halfbuy")
        self.sell = QtWidgets.QPushButton(parent=self.trade_g)
        self.sell.setGeometry(QtCore.QRect(42, 20, 72, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sell.setFont(font)
        self.sell.setStyleSheet("")
        self.sell.setObjectName("sell")
        self.halfsell = QtWidgets.QPushButton(parent=self.trade_g)
        self.halfsell.setGeometry(QtCore.QRect(4, 20, 41, 41))
        self.halfsell.setStyleSheet("")
        self.halfsell.setObjectName("halfsell")
        self.buy = QtWidgets.QPushButton(parent=self.trade_g)
        self.buy.setGeometry(QtCore.QRect(118, 20, 72, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buy.setFont(font)
        self.buy.setStyleSheet("")
        self.buy.setObjectName("buy")
        self.close1_b = QtWidgets.QPushButton(parent=self.trade_g)
        self.close1_b.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.close1_b.setObjectName("close1_b")
        self.closall_b = QtWidgets.QPushButton(parent=self.trade_g)
        self.closall_b.setGeometry(QtCore.QRect(116, 100, 101, 31))
        self.closall_b.setObjectName("closall_b")
        self.freerisk_b = QtWidgets.QPushButton(parent=self.trade_g)
        self.freerisk_b.setGeometry(QtCore.QRect(116, 70, 101, 31))
        self.freerisk_b.setObjectName("freerisk_b")
        self.close2_b = QtWidgets.QPushButton(parent=self.trade_g)
        self.close2_b.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.close2_b.setObjectName("close2_b")
        self.halfbuy.raise_()
        self.buy.raise_()
        self.sell.raise_()
        self.halfsell.raise_()
        self.close1_b.raise_()
        self.closall_b.raise_()
        self.freerisk_b.raise_()
        self.close2_b.raise_()
        self.settings_g = QtWidgets.QGroupBox(parent=Form)
        self.settings_g.setGeometry(QtCore.QRect(250, 10, 260, 193))
        self.settings_g.setObjectName("settings_g")
        self.mt5terminalpath_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.mt5terminalpath_t.setGeometry(QtCore.QRect(110, 20, 141, 20))
        self.mt5terminalpath_t.setObjectName("mt5terminalpath_t")
        self.label = QtWidgets.QLabel(parent=self.settings_g)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_3.setObjectName("label_3")
        self.close1_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.close1_t.setGeometry(QtCore.QRect(80, 130, 30, 20))
        self.close1_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.close1_t.setObjectName("close1_t")
        self.label_4 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_4.setGeometry(QtCore.QRect(150, 130, 61, 21))
        self.label_4.setObjectName("label_4")
        self.drawdown_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.drawdown_t.setGeometry(QtCore.QRect(210, 70, 41, 20))
        self.drawdown_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drawdown_t.setObjectName("drawdown_t")
        self.label_5 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_5.setGeometry(QtCore.QRect(140, 70, 71, 21))
        self.label_5.setObjectName("label_5")
        self.start_b = QtWidgets.QPushButton(parent=self.settings_g)
        self.start_b.setGeometry(QtCore.QRect(130, 160, 130, 31))
        self.start_b.setCheckable(False)
        self.start_b.setChecked(False)
        self.start_b.setObjectName("start_b")
        self.save_b = QtWidgets.QPushButton(parent=self.settings_g)
        self.save_b.setGeometry(QtCore.QRect(0, 160, 65, 31))
        self.save_b.setObjectName("save_b")
        self.userpassserver_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.userpassserver_t.setGeometry(QtCore.QRect(110, 40, 141, 20))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.userpassserver_t.setFont(font)
        self.userpassserver_t.setTabletTracking(False)
        self.userpassserver_t.setInputMask("")
        self.userpassserver_t.setText("")
        self.userpassserver_t.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.userpassserver_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userpassserver_t.setObjectName("userpassserver_t")
        self.label_21 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.label_21.setObjectName("label_21")
        self.load_b = QtWidgets.QPushButton(parent=self.settings_g)
        self.load_b.setGeometry(QtCore.QRect(65, 160, 65, 31))
        self.load_b.setObjectName("load_b")
        self.close2_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.close2_t.setGeometry(QtCore.QRect(110, 130, 30, 20))
        self.close2_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.close2_t.setObjectName("close2_t")
        self.label_11 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_11.setGeometry(QtCore.QRect(140, 100, 71, 21))
        self.label_11.setObjectName("label_11")
        self.minsl_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.minsl_t.setGeometry(QtCore.QRect(210, 100, 41, 20))
        self.minsl_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minsl_t.setObjectName("minsl_t")
        self.label_15 = QtWidgets.QLabel(parent=self.settings_g)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_15.setObjectName("label_15")
        self.symbol_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.symbol_t.setGeometry(QtCore.QRect(70, 70, 61, 20))
        self.symbol_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.symbol_t.setObjectName("symbol_t")
        self.riskperc_t = QtWidgets.QLineEdit(parent=self.settings_g)
        self.riskperc_t.setGeometry(QtCore.QRect(80, 100, 41, 20))
        self.riskperc_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.riskperc_t.setObjectName("riskperc_t")
        self.fixedlot_t = QtWidgets.QDoubleSpinBox(parent=self.settings_g)
        self.fixedlot_t.setGeometry(QtCore.QRect(201, 130, 51, 22))
        self.fixedlot_t.setMinimum(0.0)
        self.fixedlot_t.setMaximum(100.0)
        self.fixedlot_t.setSingleStep(0.01)
        self.fixedlot_t.setProperty("value", 0.0)
        self.fixedlot_t.setObjectName("fixedlot_t")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(250, 205, 261, 81))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.avatar_image = QtWidgets.QLabel(parent=self.groupBox)
        self.avatar_image.setGeometry(QtCore.QRect(2, 5, 70, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatar_image.sizePolicy().hasHeightForWidth())
        self.avatar_image.setSizePolicy(sizePolicy)
        self.avatar_image.setMinimumSize(QtCore.QSize(60, 60))
        self.avatar_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.avatar_image.setText("")
        self.avatar_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.avatar_image.setObjectName("avatar_image")
        self.frame_6 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_6.setGeometry(QtCore.QRect(75, 5, 180, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.frame_6)
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_ll_4 = QtWidgets.QLabel(parent=self.frame)
        self.username_ll_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.username_ll_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.username_ll_4.setObjectName("username_ll_4")
        self.horizontalLayout.addWidget(self.username_ll_4)
        self.telegramname_l = QtWidgets.QLabel(parent=self.frame)
        self.telegramname_l.setStyleSheet("color: rgb(0, 0, 0);")
        self.telegramname_l.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.telegramname_l.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.telegramname_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.telegramname_l.setWordWrap(False)
        self.telegramname_l.setObjectName("telegramname_l")
        self.horizontalLayout.addWidget(self.telegramname_l)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.username_ll = QtWidgets.QLabel(parent=self.frame_2)
        self.username_ll.setStyleSheet("color: rgb(0, 0, 0);")
        self.username_ll.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.username_ll.setObjectName("username_ll")
        self.horizontalLayout_2.addWidget(self.username_ll)
        self.username_l = QtWidgets.QLabel(parent=self.frame_2)
        self.username_l.setStyleSheet("color: rgb(0, 0, 0);")
        self.username_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.username_l.setObjectName("username_l")
        self.horizontalLayout_2.addWidget(self.username_l)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.server_ll = QtWidgets.QLabel(parent=self.frame_3)
        self.server_ll.setStyleSheet("color: rgb(0, 0, 0);")
        self.server_ll.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.server_ll.setObjectName("server_ll")
        self.horizontalLayout_3.addWidget(self.server_ll)
        self.server_l = QtWidgets.QLabel(parent=self.frame_3)
        self.server_l.setStyleSheet("color: rgb(0, 0, 0);")
        self.server_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.server_l.setObjectName("server_l")
        self.horizontalLayout_3.addWidget(self.server_l)
        self.verticalLayout.addWidget(self.frame_3)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 231, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(3, 15, 110, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.RR_closepct_1 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.RR_closepct_1.setGeometry(QtCore.QRect(60, 40, 41, 20))
        self.RR_closepct_1.setObjectName("RR_closepct_1")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(2, 42, 51, 16))
        self.label_18.setObjectName("label_18")
        self.RR_profitpct_1 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.RR_profitpct_1.setGeometry(QtCore.QRect(60, 20, 41, 20))
        self.RR_profitpct_1.setObjectName("RR_profitpct_1")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(2, 22, 51, 16))
        self.label_17.setObjectName("label_17")
        self.RR1 = QtWidgets.QCheckBox(parent=self.groupBox_4)
        self.RR1.setGeometry(QtCore.QRect(45, 65, 29, 22))
        self.RR1.setText("")
        self.RR1.setObjectName("RR1")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(117, 15, 110, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.RR_closepct_2 = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.RR_closepct_2.setGeometry(QtCore.QRect(60, 40, 41, 20))
        self.RR_closepct_2.setObjectName("RR_closepct_2")
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(2, 42, 51, 16))
        self.label_24.setObjectName("label_24")
        self.RR_profitpct_2 = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.RR_profitpct_2.setGeometry(QtCore.QRect(60, 20, 41, 20))
        self.RR_profitpct_2.setObjectName("RR_profitpct_2")
        self.label_25 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(2, 22, 51, 16))
        self.label_25.setObjectName("label_25")
        self.RR2 = QtWidgets.QCheckBox(parent=self.groupBox_5)
        self.RR2.setGeometry(QtCore.QRect(45, 65, 29, 22))
        self.RR2.setText("")
        self.RR2.setObjectName("RR2")
        self.table_frame = QtWidgets.QFrame(parent=Form)
        self.table_frame.setGeometry(QtCore.QRect(10, 400, 501, 141))
        self.table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.table_frame.setObjectName("table_frame")
        self.show_chart_b = QtWidgets.QPushButton(parent=self.table_frame)
        self.show_chart_b.setGeometry(QtCore.QRect(0, 110, 41, 31))
        self.show_chart_b.setObjectName("show_chart_b")
        self.nownews_l = QtWidgets.QLabel(parent=self.table_frame)
        self.nownews_l.setEnabled(True)
        self.nownews_l.setGeometry(QtCore.QRect(0, 60, 501, 20))
        self.nownews_l.setStyleSheet("")
        self.nownews_l.setScaledContents(False)
        self.nownews_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nownews_l.setObjectName("nownews_l")
        self.calendar_table = QtWidgets.QTableWidget(parent=self.table_frame)
        self.calendar_table.setEnabled(True)
        self.calendar_table.setGeometry(QtCore.QRect(0, 0, 501, 141))
        self.calendar_table.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.calendar_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.calendar_table.setAlternatingRowColors(True)
        self.calendar_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.calendar_table.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.calendar_table.setShowGrid(True)
        self.calendar_table.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.calendar_table.setCornerButtonEnabled(False)
        self.calendar_table.setRowCount(0)
        self.calendar_table.setColumnCount(5)
        self.calendar_table.setObjectName("calendar_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calendar_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calendar_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calendar_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calendar_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calendar_table.setHorizontalHeaderItem(4, item)
        self.calendar_table.horizontalHeader().setCascadingSectionResizes(False)
        self.calendar_table.horizontalHeader().setDefaultSectionSize(99)
        self.calendar_table.horizontalHeader().setMinimumSectionSize(25)
        self.calendar_table.horizontalHeader().setSortIndicatorShown(False)
        self.calendar_table.horizontalHeader().setStretchLastSection(True)
        self.calendar_table.verticalHeader().setVisible(False)
        self.calendar_table.verticalHeader().setCascadingSectionResizes(False)
        self.calendar_table.verticalHeader().setDefaultSectionSize(25)
        self.calendar_table.verticalHeader().setSortIndicatorShown(False)
        self.calendar_table.verticalHeader().setStretchLastSection(False)
        self.calendar_table.raise_()
        self.show_chart_b.raise_()
        self.nownews_l.raise_()
        self.chart_frame = QtWidgets.QFrame(parent=Form)
        self.chart_frame.setGeometry(QtCore.QRect(10, 400, 501, 141))
        self.chart_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chart_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.chart_frame.setObjectName("chart_frame")
        self.show_chart_f = QtWidgets.QFrame(parent=self.chart_frame)
        self.show_chart_f.setGeometry(QtCore.QRect(0, 0, 421, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_chart_f.sizePolicy().hasHeightForWidth())
        self.show_chart_f.setSizePolicy(sizePolicy)
        self.show_chart_f.setMinimumSize(QtCore.QSize(421, 141))
        self.show_chart_f.setMaximumSize(QtCore.QSize(421, 141))
        self.show_chart_f.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.show_chart_f.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.show_chart_f.setObjectName("show_chart_f")
        self.frame_8 = QtWidgets.QFrame(parent=self.chart_frame)
        self.frame_8.setGeometry(QtCore.QRect(420, 0, 81, 141))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.show_chart_ch = QtWidgets.QCheckBox(parent=self.frame_8)
        self.show_chart_ch.setGeometry(QtCore.QRect(30, 80, 29, 22))
        self.show_chart_ch.setText("")
        self.show_chart_ch.setObjectName("show_chart_ch")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(0, 40, 81, 41))
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.show_statement_b = QtWidgets.QPushButton(parent=self.frame_8)
        self.show_statement_b.setGeometry(QtCore.QRect(3, 10, 75, 23))
        self.show_statement_b.setObjectName("show_statement_b")
        self.show_calendar_b = QtWidgets.QPushButton(parent=self.frame_8)
        self.show_calendar_b.setGeometry(QtCore.QRect(40, 110, 41, 31))
        self.show_calendar_b.setObjectName("show_calendar_b")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_6.setGeometry(QtCore.QRect(250, 289, 261, 105))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.pos_tree = QtWidgets.QTreeWidget(parent=self.groupBox_6)
        self.pos_tree.setGeometry(QtCore.QRect(0, 0, 261, 105))
        self.pos_tree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.pos_tree.setProperty("showDropIndicator", False)
        self.pos_tree.setAlternatingRowColors(True)
        self.pos_tree.setRootIsDecorated(False)
        self.pos_tree.setExpandsOnDoubleClick(False)
        self.pos_tree.setObjectName("pos_tree")
        self.pos_tree.header().setDefaultSectionSize(51)
        self.pos_tree.header().setMinimumSectionSize(1)
        self.pos_tree.header().setSortIndicatorShown(True)
        self.pos_tree.header().setStretchLastSection(True)
        self.chart_frame.raise_()
        self.groupBox_3.raise_()
        self.settings_g.raise_()
        self.groupBox.raise_()
        self.trade_g.raise_()
        self.groupBox_2.raise_()
        self.groupBox_6.raise_()
        self.table_frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.mt5terminalpath_t, self.userpassserver_t)
        Form.setTabOrder(self.userpassserver_t, self.symbol_t)
        Form.setTabOrder(self.symbol_t, self.riskperc_t)
        Form.setTabOrder(self.riskperc_t, self.drawdown_t)
        Form.setTabOrder(self.drawdown_t, self.close1_t)
        Form.setTabOrder(self.close1_t, self.close2_t)
        Form.setTabOrder(self.close2_t, self.minsl_t)
        Form.setTabOrder(self.minsl_t, self.fixedlot_t)
        Form.setTabOrder(self.fixedlot_t, self.save_b)
        Form.setTabOrder(self.save_b, self.load_b)
        Form.setTabOrder(self.load_b, self.start_b)
        Form.setTabOrder(self.start_b, self.calendar_table)
        Form.setTabOrder(self.calendar_table, self.close1_b)
        Form.setTabOrder(self.close1_b, self.lasterror_l)
        Form.setTabOrder(self.lasterror_l, self.buy)
        Form.setTabOrder(self.buy, self.closall_b)
        Form.setTabOrder(self.closall_b, self.freerisk_b)
        Form.setTabOrder(self.freerisk_b, self.halfbuy)
        Form.setTabOrder(self.halfbuy, self.sell)
        Form.setTabOrder(self.sell, self.halfsell)
        Form.setTabOrder(self.halfsell, self.close2_b)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Trade Assistant MetaTrader5"))
        self.label_7.setText(_translate("Form", "Current Profit % :"))
        self.currentprofit_l.setText(_translate("Form", "0%"))
        self.drawdown_l.setText(_translate("Form", "0%"))
        self.label_10.setText(_translate("Form", "DrawDown % :"))
        self.label_12.setText(_translate("Form", "Last Error :"))
        self.label_13.setText(_translate("Form", "Connection : "))
        self.connection_l.setText(_translate("Form", "Disconnected!"))
        self.lasterror_l.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">-------------------------</span></p></body></html>"))
        self.trade_g.setTitle(_translate("Form", "Trade"))
        self.halfbuy.setText(_translate("Form", "/2"))
        self.sell.setText(_translate("Form", "SELL (S)"))
        self.sell.setShortcut(_translate("Form", "S"))
        self.halfsell.setText(_translate("Form", "/2"))
        self.buy.setText(_translate("Form", "BUY (B)"))
        self.buy.setShortcut(_translate("Form", "B"))
        self.close1_b.setText(_translate("Form", "Close 1 (1)"))
        self.close1_b.setShortcut(_translate("Form", "1"))
        self.closall_b.setText(_translate("Form", "Close All (A)"))
        self.closall_b.setShortcut(_translate("Form", "A"))
        self.freerisk_b.setText(_translate("Form", "Free Risk (F)"))
        self.freerisk_b.setShortcut(_translate("Form", "F"))
        self.close2_b.setText(_translate("Form", "Close 2 (2)"))
        self.close2_b.setShortcut(_translate("Form", "2"))
        self.settings_g.setTitle(_translate("Form", "Settings"))
        self.label.setText(_translate("Form", "Mt5 Terminal Path : "))
        self.label_2.setText(_translate("Form", "Risk/Pos :"))
        self.label_3.setText(_translate("Form", "Close1 | 2 % :"))
        self.close1_t.setText(_translate("Form", "30"))
        self.label_4.setText(_translate("Form", "Fixed Lot :"))
        self.drawdown_t.setText(_translate("Form", "1.5"))
        self.label_5.setText(_translate("Form", "DrawDown %:"))
        self.start_b.setText(_translate("Form", "Start (ENTER)"))
        self.start_b.setShortcut(_translate("Form", "Return"))
        self.save_b.setText(_translate("Form", "Save"))
        self.save_b.setShortcut(_translate("Form", "Ctrl+S"))
        self.label_21.setText(_translate("Form", "User:Pass:Server"))
        self.load_b.setText(_translate("Form", "Load"))
        self.load_b.setShortcut(_translate("Form", "Ctrl+L"))
        self.close2_t.setText(_translate("Form", "1"))
        self.label_11.setText(_translate("Form", "Min SL (pts):"))
        self.minsl_t.setText(_translate("Form", "1"))
        self.label_15.setText(_translate("Form", "Symbol :"))
        self.symbol_t.setText(_translate("Form", "XAUUSD"))
        self.riskperc_t.setText(_translate("Form", "0.02"))
        self.username_ll_4.setText(_translate("Form", "Name :"))
        self.telegramname_l.setText(_translate("Form", "---------------------------"))
        self.username_ll.setText(_translate("Form", "UserName:"))
        self.username_l.setText(_translate("Form", "-----------------------"))
        self.server_ll.setText(_translate("Form", "Server:"))
        self.server_l.setText(_translate("Form", "---------------------------"))
        self.groupBox_2.setTitle(_translate("Form", "Auto Trade"))
        self.groupBox_4.setTitle(_translate("Form", "RR1"))
        self.RR_closepct_1.setText(_translate("Form", "50"))
        self.label_18.setText(_translate("Form", "% Close"))
        self.RR_profitpct_1.setText(_translate("Form", "0.02"))
        self.label_17.setText(_translate("Form", "% Profit"))
        self.groupBox_5.setTitle(_translate("Form", "RR 2"))
        self.RR_closepct_2.setText(_translate("Form", "50"))
        self.label_24.setText(_translate("Form", "% Close"))
        self.RR_profitpct_2.setText(_translate("Form", "0.02"))
        self.label_25.setText(_translate("Form", "% Profit"))
        self.show_chart_b.setText(_translate("Form", ">"))
        self.nownews_l.setText(_translate("Form", "We Haven\'t News Today"))
        self.calendar_table.setSortingEnabled(False)
        item = self.calendar_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Time"))
        item = self.calendar_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Country"))
        item = self.calendar_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Impact"))
        item = self.calendar_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Title"))
        item = self.calendar_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Last Update"))
        self.label_14.setText(_translate("Form", "Using Dynamic SL"))
        self.show_statement_b.setText(_translate("Form", "Statement"))
        self.show_calendar_b.setText(_translate("Form", "<"))
        self.pos_tree.setSortingEnabled(True)
        self.pos_tree.headerItem().setText(0, _translate("Form", "Symbol"))
        self.pos_tree.headerItem().setText(1, _translate("Form", "Ticket"))
        self.pos_tree.headerItem().setText(2, _translate("Form", "Type"))
        self.pos_tree.headerItem().setText(3, _translate("Form", "Volume"))
        self.pos_tree.headerItem().setText(4, _translate("Form", "Profit"))
